# Copyright (C) 2011-2013 Project SkyFire <http://www.projectskyfire.org/>
# Copyright (C) 2008-2013 TrinityCore <http://www.trinitycore.org/>
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

language: cpp

git:
  depth: 1

branches:
  only:
    - master  
    - development

compiler:
  - gcc

before_install:
  - sudo apt-get install libace-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4

notifications:
  irc:
    channels:
      - "irc.rizon.net#project_skyfire"
    on_success: always
    on_failure: always
