#! /bin/bash
SKYFIRE_DIR='/opt/skyfire_one/';
RETVAL=0;
 
start(){
	screen -AmdS skyfire_restarter ${SKYFIRE_DIR}restarter
}
stop(){
	screen -dr skyfire_restarter -X "quit"
}
 
start-realm(){
	screen -AmdS skyfire_realm ${SKYFIRE_DIR}bin/skyfire-realm -c ${SKYFIRE_DIR}etc/authserver.conf
}
stop-realm(){
	screen -dr skyfire_realm -X "quit"
}
 
start-core(){
    cd ${SKYFIRE_DIR}
	screen -AmdS skyfire_core ${SKYFIRE_DIR}bin/skyfire-core -c ${SKYFIRE_DIR}etc/worldserver.conf
}
stop-core(){
	screen -dr skyfire_core -X "quit"
}
 
case $1 in
start)
	start;
	date;
	echo "Restarter started";
;;
stop)
	stop;
	stop-realm;
	stop-core;
	date;
	echo "Restarter stopped";
;;
restart)
	stop;
	start;
	stop-realm;
	stop-core;
	start-realm;
	start-core;
	start;
	date;
	echo "Restarter restarted";
;;
start-realm)
	start-realm;
	date;
	echo "Realm started";
;;
stop-realm)
	stop-realm;
	date;
	echo "Realm stopped";
;;
restart-realm)
	stop-realm;
	start-realm;
	date;
	echo "Realm restarted";
;;
start-core)
	start-core;
	date;
	echo "Core started";
;;
stop-core)
	stop-core;
	date;
	echo "Core stopped";
;;
restart-core)
	stop-core;
	start-core;
	date;
	echo "Core restarted";
;;
start-restarter)
	start;
	date;
	echo "Restarter Démarre";
;;
stop-restarter)
	stop;
	date;
	echo "Restarter stopped";
;;
restart-restarter)
	stop;
	start;
	date;
	echo "Restarter restarted";
;;
status)
	screen -ls
;;
restarter)
	screen -r skyfire_restarter
;;
realm)
	screen -r skyfire_realm
;;
core)
	screen -r skyfire_core
;;
*)
	echo "Usage: $0 {start|stop|restart|start-realm|stop-realm|restart-realm|start-core|stop-core|restart-core|start-restarter|stop-restarter|restart-restarter|status|restarter|realm|core}"
	RETVAL=1
esac
exit $RETVAL;
