ALTER TABLE characters
  ADD COLUMN `exploredZones` LONGTEXT AFTER latency,
  ADD COLUMN `equipmentCache` LONGTEXT AFTER exploredZones,
  ADD COLUMN `ammoId` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER equipmentCache,
  ADD COLUMN `knownTitles` LONGTEXT AFTER ammoId;

UPDATE characters SET
exploredZones = SUBSTRING(DATA,
LENGTH(SUBSTRING_INDEX(DATA, ' ', 1041))+2,
LENGTH(SUBSTRING_INDEX(DATA, ' ', 1168+1))- LENGTH(SUBSTRING_INDEX(DATA, ' ', 1041)) - 1),
equipmentCache = SUBSTRING(DATA,
LENGTH(SUBSTRING_INDEX(DATA, ' ', 283))+2,
LENGTH(SUBSTRING_INDEX(DATA, ' ', 320+1))- LENGTH(SUBSTRING_INDEX(DATA, ' ', 283)) - 1),
ammoId = SUBSTRING(DATA,
LENGTH(SUBSTRING_INDEX(DATA, ' ', 1198))+2,
LENGTH(SUBSTRING_INDEX(DATA, ' ', 1198+1))- LENGTH(SUBSTRING_INDEX(DATA, ' ', 1198)) - 1),
knownTitles = SUBSTRING(DATA,
LENGTH(SUBSTRING_INDEX(DATA, ' ', 626))+2,
LENGTH(SUBSTRING_INDEX(DATA, ' ', 631+1))- LENGTH(SUBSTRING_INDEX(DATA, ' ', 626)) - 1);

ALTER TABLE characters
  DROP COLUMN DATA;
